// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn2QOi4yOCwBG2LNez3fxw_7Za2iGJGLc',
    appId: '1:422962188365:web:f557e418eb4140217d8c04',
    messagingSenderId: '422962188365',
    projectId: 'shop-issue-form-flutter',
    authDomain: 'shop-issue-form-flutter.firebaseapp.com',
    storageBucket: 'shop-issue-form-flutter.appspot.com',
    measurementId: 'G-GMV5VY0DFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOq3hYiS2y2nDranxdIgfs0BA2Ux4Xqg',
    appId: '1:422962188365:android:7ae089a49b7165f87d8c04',
    messagingSenderId: '422962188365',
    projectId: 'shop-issue-form-flutter',
    storageBucket: 'shop-issue-form-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFzSqyttCjURnOJQB44tUaJuYJaPdajTo',
    appId: '1:422962188365:ios:6ecfe7037a945e707d8c04',
    messagingSenderId: '422962188365',
    projectId: 'shop-issue-form-flutter',
    storageBucket: 'shop-issue-form-flutter.appspot.com',
    iosClientId: '422962188365-vrncn0rhusrdp5mcb60buvqqc795l6dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopIssueFormFlutter',
  );
}
